[zli-config]
refresh-interval = "10h"

[remote]
name = "origin"
branch = "main"

[acme]
domain = [
    "a.qiumiaomiao.tech",
    "www.qiumiaomiao.tech"
]
email = ["2268428576@qq.com"]
cache = "./acme/product/cache"
product-mode = true
listening-at = 443
forward-to = 6080