[zli-config]
refresh-interval = "10h"

[remote]
name = "origin"
branch = "main"

[acme]
domain = ["a.qiumiaomiao.tech"]
email = ["2268428576@qq.com"]
cache = "./acme/catch"
product-mode = false
listening-at = 80
forward-to = 6080